CREATE TABLE IF NOT EXISTS bots (id TEXT NOT NULL PRIMARY KEY, grammar JSON, token TEXT NOT NULL, secret TEXT NOT NULL, updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);

-- Make sure all columns exist
ALTER TABLE IF EXISTS bots
    ADD COLUMN IF NOT EXISTS id TEXT NOT NULL PRIMARY KEY,
    ADD COLUMN IF NOT EXISTS grammar JSON,
    ADD COLUMN IF NOT EXISTS token TEXT NOT NULL,
    ADD COLUMN IF NOT EXISTS secret TEXT NOT NULL,
    ADD COLUMN IF NOT EXISTS updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
